# Generated by Django 5.2.8 on 2025-11-26 06:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0087_alter_collectionreport_responsibility_center_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerepairaccreditationapplication',
            name='acknowledgment_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerepairaccreditationapplication',
            name='payment_status',
            field=models.CharField(choices=[('awaiting', 'Awaiting Payment'), ('paid', 'Paid'), ('verified', 'Verified')], default='awaiting', max_length=20),
        ),
        migrations.AddField(
            model_name='servicerepairaccreditationapplication',
            name='reference_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='servicerepairaccreditationapplication',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
