# Generated by Django 5.2.8 on 2025-11-26 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0012_remove_user_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=20, null=True)),
                ('action_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Failed Login'), ('page_view', 'Page Visit'), ('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('upload', 'Uploaded File'), ('payment_initiated', 'Payment Initiated'), ('payment_verified', 'Payment Verified'), ('payment_failed', 'Payment Failed'), ('refund_initiated', 'Refund Initiated'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('submitted', 'Submitted'), ('session_expired', 'Session Expired'), ('password_changed', 'Password Changed'), ('email_changed', 'Email Changed')], max_length=30)),
                ('action', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('visibility', models.CharField(choices=[('private', 'Private (User only)'), ('public', 'All users')], default='private', max_length=20)),
                ('object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='users_activ_user_id_8a5363_idx'), models.Index(fields=['action_type', '-timestamp'], name='users_activ_action__961327_idx')],
            },
        ),
    ]
