# Generated by Django 5.2.8 on 2025-11-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('unverified_owner', 'Unverfied Owner'), ('business_owner', 'Business Owner'), ('admin', 'Admin'), ('collection_agent', 'Collection Agent'), ('alt_collection_agent', 'Alternative Collection Agent'), ('authorized_official', 'Authorized Official')], default='unverified_owner', max_length=20),
        ),
    ]
